account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import  ArticleList, ArticleCreate

app_name = "account"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    # path("logout/", views.LogoutView.as_view(), name="logout"),
    # path(
    #     "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    # ),
    # path(
    #     "password_change/done/",
    #     views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    # path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    # path(
    #     "password_reset/done/",
    #     views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    # path(
    #     "reset/<uidb64>/<token>/",
    #     views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm",
    # ),
    # path(
    #     "reset/done/",
    #     views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
]

urlpatterns += [
    path('', ArticleList.as_view(), name="home"),
    path('article/create', ArticleCreate.as_view(), name="article-create"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('pages.urls')),
    path("account/", include('account.urls')),
]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import ArticleList, ArticleDetail, CategoryList, AuthorList

app_name = "pages"
urlpatterns = [
    path("", ArticleList.as_view(), name = 'home'),
    path("page/<int:page>", ArticleList.as_view(), name = 'home'),
    path("article/<slug:slug>", ArticleDetail.as_view(), name = 'detail'),
    path("category/<slug:slug>", CategoryList.as_view(), name = 'category'),
    path("category/<slug:slug>/page/<int:page>", CategoryList.as_view(), name = 'category'),
    path("author/<slug:username>", AuthorList.as_view(), name = 'author'),
    path("author/<slug:username>/page/<int:page>", AuthorList.as_view(), name = 'author')
]

account/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
	is_author = models.BooleanField(default=False, verbose_name="وضعیت نویسندگی")
	special_user = models.DateTimeField(default=timezone.now, verbose_name="کاربر ویژه تا")

	def is_special_user(self):
		if self.special_user > timezone.now():
			return True
		else:
			return False

	is_special_user.boolean = True
	is_special_user.short_description = 'وضعیت کاریر ویژه'

pages/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils.html import format_html
from django.utils import timezone
from extentions.utils import jalali_convertor


#my managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)

# Create your models here.
class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True,blank=True,on_delete=models.SET_NULL,related_name='children',verbose_name='زیر دسته')
    title = models.CharField(max_length=200,verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length=250, unique=True, verbose_name="آدرس مقاله")
    status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")
    position = models.IntegerField(verbose_name="پوزیشن")


    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ["parent__id","position"]

    def __str__(self):
        return self.title

    objects = CategoryManager()




class Article(models.Model):
    STATUSE_CHOICES = (
        ('d', 'پیشنویس'),
        ('p', 'منتشر شده'),
        )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL,related_name='articles',verbose_name='نویسنده')
    title = models.CharField(max_length=200,verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=250, unique_for_date='publish',verbose_name="آدرس مقاله")
    category = models.ManyToManyField(Category,verbose_name="دسته بندی",related_name='articles')
    description = models.TextField(verbose_name="محتوا")
    thumbnail = models.ImageField(upload_to="images",verbose_name="تصویر مقاله")
    publish = models.DateTimeField(default=timezone.now,verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,choices=STATUSE_CHOICES,verbose_name="وضعیت")


    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ['-publish']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("account:home")


    def jpublish(self):
        return jalali_convertor(self.publish)
    jpublish.short_description = "زمان انتشار"
    
    def thumbnail_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 50px;' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description = "عکس" 


    def category_to_str(self):
        return ",".join([category.title for category in self.category.active()])
    category_to_str.short_description = "دسته بندی"

    objects = ArticleManager()

account/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,CreateView
from pages.models import Article

# Create your views here.
class ArticleList(LoginRequiredMixin, ListView):
	template_name = "registration/home.html"

	def get_queryset(self):
		if self.request.user.is_superuser:
			return Article.objects.all()
		else:
			return Article.objects.filter(author=self.request.user)
class ArticleCreate(LoginRequiredMixin, CreateView):
	model = Article
	fields = ["author", "title", "slug", "category", "description", "thumbnail", "publish", "status"]
	template_name = "registration/article-create-update.html"

pages/views.py
from django.core.paginator import Paginator
from django.views.generic import ListView,DetailView
from django.contrib.auth.models import User
from django.shortcuts import render,get_object_or_404
# from django.http import HttpResponse, JsonResponse
from .models import Article , Category


# Create your views here.
class ArticleList(ListView):
    # model = Article
    # template_name = "pages/home.html"
    # context_object_name = 'articles'
    queryset = Article.objects.published()
    paginate_by = 6


class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(),slug=slug)


class CategoryList(ListView):
    paginate_by = 3
    template_name = "pages/category_list.html"

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(),slug=slug)
        return category.articles.published()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context
    
class AuthorList(ListView):
    paginate_by = 3
    template_name = "pages/author_list.html"

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User,username=username)
        return author.articles.published()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

pages/templates/pages/list.html
{% extends 'pages/base.html' %}
{% load static %}
{% block main %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static "pages/assets/img/home-bg.jpg" %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>پایتون لرنینگ</h1>
                            
                        </div>
                    </div>
                </div>
            </div>
        </header>
 <!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% block header %}{% endblock %}
          {% for article in object_list %}
          <div class="post-preview">
            <a href="{% url 'pages:detail' article.slug %}">
                <h2 class="post-title">
                    {{article.title}}

                </h2>
                <h3 class="post-subtitle">
                    {{article.description|truncatewords:30}}
                </h3>
            </a>
            <p class="post-meta">
                نوشته شده توسط
                <a href="#!">برنامه نویس</a>
                {{article.jpublish}}
            </p>
            <div>
                {% for cat in article.category.active %}
                <a href="{% url 'pages:category' cat.slug %}">#{{cat.title}}</a>
                {% endfor %}
            </div>
        </div>
        <hr>
          {% endfor %}
            <!-- Pager-->
            {% if is_paginated %}
            <div class="d-flex justify-content-end mb-4 pager-buttom">
                {% if page_obj.has_previous %}
                <a class="btn btn-primary text-uppercase ml-3" href="{% block previous_page_url %}{% endblock %}">پست های  جدید  &rarr;</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary text-uppercase " href="{% block next_page_url %}{% endblock %}"> پست های قدیمی  &larr;</a>
                {% endif %} 
             </div>
         {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/pages/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/pages/article_detail.html
{% extends 'pages/base.html' %}

{% block title %}
  {{object.title}}
{% endblock %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{object.thumbnail.url}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{object.title}}</h1>
            <time>{{object.jpublish}}</time>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-justify">
          {{object.description|safe}}
        </div>
      </div>
    </div>
  </article>
{% endblock %}

templates/pages/article_list.html
{% extends 'pages/list.html' %}

{% block header %}{% endblock %}

{% block previous_page_url %}
  {% url 'pages:home' page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
  {% url 'pages:home' page_obj.next_page_number %}
{% endblock %}

templates/pages/author_list.html
{% extends 'pages/list.html' %}

{% block header %}
	<h3 class="alert alert-primary text-center">نویسنده: {{author.get_full_name}}</h3>
{% endblock %}

{% block previous_page_url %}
	{% url 'pages:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
	{% url 'pages:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/pages/base.html
 {% load static %}
 {% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>آکادمی جواد{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="{% static 'pages /https://use.fontawesome.com/releases/v6.1.0/js/all.js' %}" crossorigin="anonymous"></script>

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'pages/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'pages/css/artl.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'pages:home' %}">{%  title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>

        {% block main %}
        {% endblock %}

        <hr>

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'pages/ttps://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'pages/js/scripts.js' %}"></script>
    </body>
</html>

templates/pages/category_list.html
{% extends 'pages/list.html' %}

{% block header %}
	<h3 class="alert alert-primary text-center">دسته‌بندی: {{category.title}}</h3>
{% endblock %}

{% block previous_page_url %}
	{% url 'pages:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
	{% url 'pages:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/pages/list.html
{% extends 'pages/base.html' %}
{% load static %}
{% block main %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static "pages/assets/img/about-bg.jpg" %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>پایتون لرنینگ</h1>
                            
                        </div>
                    </div>
                </div>
            </div>
        </header>
 <!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% block header %}{% endblock %}
          {% for article in object_list %}
          <div class="post-preview">
            <a href="{% url 'pages:detail' article.slug %}">
                <h2 class="post-title">
                    {{article.title}}

                </h2>
                <h3 class="post-subtitle">
                    {{article.description|striptags|truncatewords:30}}
                </h3>
            </a>
            <p class="post-meta">
                نوشته شده توسط
                <a href="{% url 'pages:author' article.author %}">{{article.author.get_full_name}} </a>
                {{article.jpublish}}
            </p>
            <div>
                {% for cat in article.category.active %}
                <a href="{% url 'pages:category' cat.slug %}">#{{cat.title}}</a>
                {% endfor %}
            </div>
        </div>
        <hr>
          {% endfor %}
            <!-- Pager-->
            {% if is_paginated %}
            <div class="d-flex justify-content-end mb-4 pager-buttom">
                {% if page_obj.has_previous %}
                <a class="btn btn-primary text-uppercase ml-3" href="{% block previous_page_url %}{% endblock %}">پست های  جدید  &rarr;</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary text-uppercase " href="{% block next_page_url %}{% endblock %}"> پست های قدیمی  &larr;</a>
                {% endif %} 
             </div>
         {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/pages/partials/category_loop.html
<ul class="navbar-nav ml-auto">
  {% for cat in cat.children.active %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'pages:category' cat.slug %}">{{cat.title}}</a>
        {% if cat.children.all %}
            {% include 'pages/partials/category_loop.html' %}
        {% endif %}
    </li>
  {% endfor %}
</ul> 

templates/pages/partials/category_navbar.html
<div class="collapse navbar-collapse nav" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'pages:home' %}">خانه</a>
    </li>
    {% for cat in category %}
        {% if cat.parent == None %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:category' cat.slug %}">{{cat.title}}</a>
                 {% if cat.children.active %}
                    {% include 'pages/partials/category_loop.html' %}
                 {% endif %}
            </li>    
         {% endif %}
    {% endfor %}
    </ul>
</div> 